OneBusAway/wayfinder

src/components/ArrivalDeparture.svelte, src/components/oba/StopPane.svelte
Tasks done:
- Removed the textarea containing JSON.stringify() information.
- Created a new ArrivalDeparture component that resembles the iOS screenshot you provided.
- Rendered the list of ArrivalDeparture components from the data loaded from the server and displayed them in StopPane.
Output:
=> Fixes #1: Improve the Look and Feel of StopPane

src/components/ArrivalDeparture.svelte, src/components/map/GoogleMap.svelte, src/components/navigation/Header.svelte, src/components/oba/StopPane.svelte, src/lib/ThemeSwitch/ThemeSwitcher.svelte, src/lib/googleMaps.js, src/lib/utils.js, src/routes/+page.svelte, tailwind.config.js
Fixes #5
**Tasks done:**
- Implemented proper support for Dark Mode using Tailwind's dark variant.
- Ensured the map theme persisted based on user preference (light/dark) upon page reload.
- The spinner displays while bus stop data is being fetched, improving the user experience by indicating loading status.
- Ensured consistent theme handling across different components.
**Screenshot:**
=> Added Dark Mode support to web app

src/components/oba/StopPane.svelte, src/lib/keybinding.js
Fixes https://github.com/OneBusAway/onebusaway-webapp/issues/15
=> Closes the StopPane when the Escape key is pressed on the keyboard

src/components/navigation/ModalPane.svelte, src/components/oba/StopPane.svelte, src/routes/+page.svelte, svelte.config.js
* Extract reusable ModalPane from StopPane
* Fill in some more information on the StopPane
=> Couple small improvements

.github/workflows/test.yml
Fixes #14 
**Tasks done:**
- created the `test.yml` file in the github/workflows.
=> added the test file to run tests as part of CI

src/routes/+layout.svelte
Fixes #38 
**Done:**
Header element added to the stop page.
=> fix: header added to stop page

src/components/oba/TripDetailsPane.svelte
=> fix: time formatting issue

src/routes/+page.svelte
=> fix: Hide viewAllRoutes modal when a stop is selected

src/components/oba/StopPane.svelte
=> feat: load arrivalsAndDepartures data when new stop selected

src/lib/Provider/OpenStreetMapProvider.js
=> refactor: Disable Map Rotation on Right-Click Drag in MapLibre Layer for OpenStreetMapProvider

src/components/map/StopMarker.svelte
=> fix: ensure direction arrows are visible in dark mode

src/routes/api/oba/alerts/+server.js
=> fix: enable test alerts display in test mode

src/components/search/SearchField.svelte
=> fix: prevent empty search submissions and disable button accordingly

vite.config.js
=> feat: Enable top-level await support in esbuild configuration

package.json, src/index.test.js, src/tests/lib/formatters.test.js
=> Adds our first 'real' unit tests

package-lock.json, package.json
=> chore: update onebusaway-sdk to version 1.6.0 in package.json and package-lock.json

src/components/surveys/HeroQuestion.svelte
=> Add dark mode support (Surveys)

src/components/trip-planner/LegDetails.svelte
=> Add tram icon

src/components/map/PopupContent.svelte, src/components/oba/TripDetailsPane.svelte, src/lib/formatters.js, src/tests/lib/formatters.test.js
=> refactor: replace convertUnixToTime with formatSecondsFromMidnight for arrival time formatting

src/components/map/PopupContent.svelte, src/components/map/RouteMap.svelte, src/components/search/SearchPane.svelte, src/components/search/__tests__/SearchPane.test.js, src/lib/Provider/GoogleMapProvider.svelte.js, src/lib/Provider/OpenStreetMapProvider.svelte.js, src/routes/+page.svelte, src/tests/mocks/mapProviders.js
Fixes #254
* refactor: rename addStopMarker to addStopRouteMarker for consistency
* feat: bind handleStopMarkerSelect to the component for stop selection
* feat: integrate handleStopMarkerSelect for improved stop marker handling and update test mocks for consistency
* feat: add delay to handleStopMarkerSelect for improved stop selection timing
* fix: conditionally render arrival time in PopupContent component
=> fix: Clicking on search results not displaying stop info window
