OneBusAway/wayfinder

- src/components/map/GoogleMap.svelte
Fixed #2 
**Tasks done:**
- Added a debounce function to ensure the loadStopsAndAddMarkers function is not called more frequently than once every 300 milliseconds.
- The loadStopsAndAddMarkers function fetches stops for the current center of the map and adds markers after checking for duplicates.
- The markerExists function checks if a marker for a specific stop ID already exists.
**Screenshot:**
> Fixes #2: Improve map functionality to load more stops on pan and zoom

- .github/workflows/lint.yml
- package.json
Fixes #13 
**Tasks Done**
- Cache npm install artifacts
- More verbose error reporting from the prettier and eslint commands.
**Files Changed:**
All modifications done within the `.github/workflows/lint.yml` file
> Improved the CI Workflow

- src/components/navigation/Header.svelte
Fixes #20 
**Tasks done:**
- Added the logo in the navbar (with some roundness for better UI)
- The logo URL is added in the .env file (currently using the imgur for uploading the logo to get the URL).
The logo is wrapped in a hyperlink that navigates back to the root path and use the value of PUBLIC_OBA_REGION_NAME for its alt attribute.
> Changed the Region Name text to OBA Logo

- src/components/map/GoogleMap.svelte
- src/components/navigation/ModalPane.svelte
- src/components/oba/StopPane.svelte
- src/lib/RestAPI/arrivalsAndDeparturesForStop.js
- src/lib/RestAPI/stop.js
- src/routes/api/oba/arrivals-and-departures-for-stop/[id]/+server.js
- src/routes/api/oba/stop/[stopID]/+server.js
- src/routes/stops/[stopID]/+page.server.js
- src/routes/stops/[stopID]/+page.svelte
- svelte.config.js
> Adds Stop Details Page

- package-lock.json
- package.json
- src/components/ArrivalDeparture.svelte
- src/components/map/GoogleMap.svelte
- src/components/navigation/ModalPane.svelte
- src/components/navigation/TripDetailsModal.svelte
- src/components/oba/StopPane.svelte
- src/components/oba/TripDetailsPane.svelte
- src/lib/RestAPI/arrivalsAndDeparturesForStop.js
- src/lib/RestAPI/stop.js
- src/lib/RestAPI/tripDetails.js
- src/routes/api/oba/trip-details/[tripId]/+server.js
- src/routes/stops/[stopID]/+page.server.js
- src/routes/stops/[stopID]/+page.svelte
> added the api for trip details, created the tripdetailpane with all information

- src/components/map/GoogleMap.svelte
- src/components/map/RouteMap.svelte
- src/components/oba/StopPane.svelte
- src/components/oba/TripDetailsPane.svelte
- src/lib/googleMaps.js
- src/routes/+page.svelte
- src/routes/api/oba/shape/[shapeId]/+server.js
> Implemented the Bus Route, Draw polyline feat, and hidden unrelated stops

- src/components/map/GoogleMap.svelte
- src/components/oba/StopPane.svelte
- src/routes/+page.svelte
> Added the feature for hiding the bus route on back to button

- src/components/map/GoogleMap.svelte
Currently, when a user searches for a stop, the URL doesn't change according to the searched selected stop.
Now, the URL changes when the user searches for a stop or route.
> fix: added the url pushstate when search for a stop/route

- src/components/map/GoogleMap.svelte
- src/components/map/StopMarker.svelte
- src/config/routeConfig.js
Fixes #39 
Added the feature to show the correct icon type on the map according to the priority OBA provides.
> Feat: show the correct icon type according to priority

- src/components/navigation/ModalPane.svelte
- src/routes/+layout.svelte
> Fix: ModalPane never underlap the top of the window or navbar

- src/components/map/RouteMap.svelte
[Commit 1](https://github.com/OneBusAway/onebusaway-webapp/pull/49/commits/1bca64c181fe105137e869e7ee62df5c3a45ee50)
**Issue** 
Earlier the **stop name** in trip route didn't show in dark mode. 
**Fixes**
Added the styles for dark mode for stop name.
[Commit 2](https://github.com/OneBusAway/onebusaway-webapp/pull/49/commits/864068fe10e631c19685f871659720dadeeeec96)
**Fixes**
Added the background to the InfoWindow's arrival time.
**Screenshot**
**Note:** Ignore the yellow border (its just selected in my window).
> Added some UI Enhancements

- eslint.config.js
- package-lock.json
- package.json
- src/assets/styles/leaflet-map.css
- src/components/MapContainer.svelte
- src/components/map/GoogleMap.svelte
- src/components/map/MapView.svelte
- src/components/map/PopupContent.svelte
- src/components/map/RouteMap.svelte
- src/config/mapSource.js
- src/lib/MapTypeButton/MapTypeButton.svelte
- src/lib/Provider/GoogleMapProvider.js
- src/lib/Provider/OpenStreetMapProvider.js
- src/routes/+page.svelte
- svelte.config.js
**Tasks Completed:**
- Added the osm support at `.env` level
- Created the `GoogleMapProvider `& `OpenStreetMapProvider` classes as providers.
- Implemented the plugin architecture for other maps in future.
**Issues In-progress:**
- change icons in OSM
- display the route in OSM & google maps
- display stops properly in google maps
> Add support for OpenStreetMap

- src/app.css
- src/components/ArrivalDeparture.svelte
- src/components/map/StopMarker.svelte
- src/components/navigation/ModalPane.svelte
- src/components/oba/StopPane.svelte
- src/components/oba/TripDetailsPane.svelte
Fit and finish, improving color contrast, etc.
> Dark mode improvements

- src/components/search/SearchField.svelte
- src/components/search/SearchPane.svelte
**Issue**
Earlier, the search icon hover was not visible and lacked color improvements. 
**Fixes**
-  Fixed the search icon color on hover.
- Added a shadow to the search box in dark mode.
**Screenshots**
> Search Box UI Fixes

- src/components/navigation/Header.svelte
- src/components/navigation/MobileMenu.svelte
**Issue:**
Currently, the header is not responsive, and users aren't able to use the header on small screens like mobiles, etc.
**Fixes:** #6 
Added the responsiveness to the header/navbar.
**Screenshot:**
> feat: added the responsiveness to the header

- src/app.css
- src/assets/styles/leaflet-map.css
- src/components/navigation/ModalPane.svelte
- src/components/navigation/ViewAllRoutesModal.svelte
- src/components/search/SearchPane.svelte
- src/routes/+layout.svelte
- src/routes/+page.svelte
Fixes #71
The modal pane was feeling a bit wide, and looked a bit strange with its margins not lining up with the search box. This change reconsiders how we render the search box and modals to make them 'physically' smaller and feel more connected to the rest of the UI.
* Get rid of an extra header element on the map — now we only have the single header on the layout page
* Judiciously use `.pointer-events-none` to make large swaths of our UI clickable that had not been before
* Unify/DRY up our modal pane styling so that the search pane and modal panes look similar
> Rebuilds side pane UI to fix underlaps, etc.

- src/components/navigation/RouteModal.svelte
- src/components/navigation/ViewAllRoutesModal.svelte
- src/components/oba/StopPane.svelte
Added some horizontal space between arrival/departure and route info in Stoppane.
Before:
After:
> UI Improvements

- src/components/trip-planner/TripPlan.svelte
> fix: prevent multiple location selections by locking the selection 

- src/lib/i18n.js
- vite.config.js
Fixes #150
* I'm not sure why this is necessary, as this feature is supposed to work in Safari, but... it doesn't. So, I'm disabling it for now.
* Move back to synchronous loading of locales in i18n.js to unbreak the standalone schedule and stop pages.
> Disable top-level await to fix the site in Safari

- .gitignore
- package-lock.json
- package.json
- src/tests/lib/formatters.test.js
- vite.config.js
Fixes #149 
**Changes Made:**
- Configured Vitest for code coverage in existing `vite.config.js`
- Added a new script `npm run test:coverage` to generate test coverage reports locally.
- Added coverage/ folder to `.gitignore` to prevent committing generated reports.
**Screenshot of Coverage folder:**
After running the test suite using `npm run test:coverage`, we can generate the coverage report in the coverage folder.
> Fix #149: Configured code coverage

- README.md
- package-lock.json
- package.json
- src/app.css
- src/components/ArrivalDeparture.svelte
- src/components/map/StopMarker.svelte
- src/components/map/VehiclePopupContent.svelte
- src/components/navigation/AlertsModal.svelte
- src/components/oba/TripDetailsPane.svelte
- src/components/routes/RouteModal.svelte
- src/components/search/SearchPane.svelte
- src/components/stops/StopPageHeader.svelte
- src/components/stops/StopPane.svelte
- src/components/trip-planner/LegDetails.svelte
- src/components/trip-planner/TripPlan.svelte
- tailwind.config.js
PR Fixes #155 
**Changes Done:**
- Implemented primary color customization throughout the app in major components including buttons, texts, backgrounds, etc using the APP_PRIMARY_COLOR environment variable.
- Changed the background UI of RouteModal and StopPane.
Screenshots:
> Primary Color Customization

- src/components/StandalonePage.svelte
- src/components/containers/AccordionItem.svelte
- src/components/schedule-for-stop/RouteScheduleTable.svelte
- src/routes/stops/[stopID]/schedule/+page.svelte
Fixes #164, #163 
**Screenshots:**
**Before**
**After**
> UI Improvements in Route Schedule

- src/components/MapContainer.svelte
- src/components/map/PopupContent.svelte
- src/components/routes/RouteModal.svelte
- src/lib/Provider/GoogleMapProvider.svelte.js
- src/lib/Provider/OpenStreetMapProvider.svelte.js
- src/locales/en.json
Resolves https://github.com/OneBusAway/wayfinder/issues/193 -- makes some improvements to the experience when a stop is selected within the Route Modal, namely:
- shows the popup on the map for the stop you've selected
- adds a button to that popup to allow you to open the stop modal from the popup itself.
> Open stop information on click in route modal, add button to open stop modal

- src/lib/googleMaps.js
Fixes: #214 
Removed an unused import statement to improve code cleanliness and avoid unnecessary dependencies.
> Chore: Remove unused COLORS import from googleMaps.js

- src/components/stops/StopPane.svelte
- src/routes/stops/[stopID]/schedule/+page.svelte
added conditionally rendering for the loaders and remove in other case
fixes: #191
> fix: ensure loading spinner displays only when a trip is selected

- src/components/navigation/Header.svelte
Fixes #189 
**Changes**
- Added the `measureLinksWidth` function to use actual link text for accurate width measurement.
- Ensured responsive behavior remains intact by maintaining accurate width calculations.
- Adjusted the layout and positioning of the burger icon to ensure it is correctly aligned.
Screenshot:
> Improve navbar overflow handling and simplify link width measurement

- src/lib/ThemeSwitch/ThemeSwitcher.svelte
**Changes**
- Increased website accessibility by 5% by adding `aria-label="Toggle theme"` to the checkbox input in `ThemeSwitcher.svelte`
**Screenshot**
> Improved Accessibility: Added labels to theme switcher

- src/components/stops/StopPane.svelte
This PR fixes the issue #220 where rapidly switching between stop icons caused a race condition, leading to incorrect errors.
Fixes & Improvements:
- Abort previous fetch requests before making a new one (fixes race condition).
- Wrap fetch calls in a try-catch block to properly handle errors.
- Improve error messages to provide better feedback.
- Ensure loading state resets correctly after a failed request.
> Fixed race condition in stopPane

- src/components/search/SearchPane.svelte
- src/routes/+page.svelte
A proposed organizational improvement to managing the modal in the side panel -- namely, using a single bit of state to choose which modal to show, rather than a series of booleans.
> Manage modals in single bit of state
